MTDSA-8703 Updated Controller SubmitReturn
hmrc/insolvent-vat-api pull request #17
Opened 2021-05-04 13:15 UTC by vfryer12

2021-05-05 07:36 UTC, Mbrookesy requested changes

2021-05-05 07:36 UTC, Mbrookesy commented on app/v1/controllers/SubmitReturnController.scala
> +                                      (implicit ec: ExecutionContext)
It appears that the appconfig and datetime aren't being used in the controller

2021-05-05 07:36 UTC, Mbrookesy commented on it/v1/endpoints/SubmitReturnControllerISpec.scala
> +  )
I don't believe the endpoint returns any links

2021-05-05 07:36 UTC, Mbrookesy commented on it/v1/endpoints/SubmitReturnControllerISpec.scala
> + //       response.json shouldBe mtdResponse
Comment should be taken out

2021-05-05 07:36 UTC, Mbrookesy commented on it/v1/endpoints/SubmitReturnControllerISpec.scala
> +    "return a 200 status code with expected body" should {
Status should be 201

2021-05-06 07:35 UTC, Mbrookesy approved these changes

2021-05-06 08:40 UTC, Taiwo-AB commented on app/utils/CurrentDateTime.scala
> +/*
This should be removed.

2021-05-06 08:43 UTC, Taiwo-AB commented on app/v1/controllers/SubmitReturnController.scala
> +      case VrnFormatError | PeriodKeyFormatError | RuleIncorrectOrEmptyBodyError | ValueFormatError |
Should be MtdErrorWithCustomMessage(RuleIncorrectOrEmptyBodyError.code) and MtdErrorWithCustomMessage(ValueFormatError.code)

2021-05-06 08:44 UTC, Taiwo-AB commented on app/v1/controllers/SubmitReturnController.scala
> +      case _: MtdError => BadRequest(Json.toJson(errorWrapper))
I don't think this is needed

2021-05-06 08:46 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    with MockCurrentDateTime
Remove as it is not needed

2021-05-06 08:46 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +  val date: DateTime = DateTime.parse("2017-01-01T00:00:00.000Z")
This should be removed as it is unused

2021-05-06 08:47 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +  val fmt: String = DateUtils.dateTimePattern
This should be removed as it is unused

2021-05-06 08:48 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +  val periodKey: String = "A1A2"
This should be removed as it is unused

2021-05-06 08:48 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +  val uid: String = "a5894863-9cd7-4d0d-9eee-301ae79cbae6"
This should be removed

2021-05-06 08:48 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    MockCurrentDateTime.getCurrentDate.returns(date).anyNumberOfTimes()
Please remove this

2021-05-06 08:48 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    MockIdGenerator.getUid.returns(uid).once()
Please remove this

2021-05-06 08:49 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    MockedAppConfig.apiGatewayContext.returns("baseUrl").anyNumberOfTimes()
Please remove this

2021-05-06 08:49 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +      |{
This should be removed as it is unused

2021-05-06 08:50 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    "return OK" should {
Doesn't return OK

2021-05-06 08:50 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +          (VrnFormatError, BAD_REQUEST),
This aren't the only Parser errors

2021-05-06 08:50 UTC, Mbrookesy requested changes

2021-05-06 08:50 UTC, Mbrookesy commented on app/utils/CurrentDateTime.scala
> +
Since the implementation of this was removed in the submit return controller, this file should be removed.

2021-05-06 08:50 UTC, Mbrookesy commented on test/v1/mocks/MockCurrentDateTime.scala
> +  object MockCurrentDateTime {
This file should also be deleted

2021-05-06 08:50 UTC, Mbrookesy commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    with MockCurrentDateTime
This line doesn't need to be here

2021-05-06 08:50 UTC, Mbrookesy commented on app/v1/controllers/SubmitReturnController.scala
> +      case NotFoundError => NotFound(Json.toJson(errorWrapper))
This endpoint doesn't have a not found error

2021-05-06 08:50 UTC, Mbrookesy commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +  val fmt: String = DateUtils.dateTimePattern
These lines don't appear to be used

2021-05-06 08:50 UTC, Mbrookesy commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +  val periodKey: String = "A1A2"
Same for this one

2021-05-06 08:50 UTC, Mbrookesy commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +          (NotFoundError, NOT_FOUND),
Not found doesn't need to be tested as there is no not found error

2021-05-06 08:50 UTC, Mbrookesy commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +        )
All the validation errors should be tested here, it's missing a test for 

FORMAT_VALUE
FORMAT_UNIQUE_ID
FORMAT_RECEIVED_AT

2021-05-06 08:50 UTC, Mbrookesy commented on it/v1/endpoints/SubmitReturnControllerISpec.scala
> +      )
All the validation errors should be tested here, it's missing a test for 

FORMAT_PERIOD_KEY
FORMAT_VALUE
FORMAT_UNIQUE_ID
FORMAT_RECEIVED_AT

2021-05-06 08:51 UTC, Taiwo-AB commented on app/v1/controllers/SubmitReturnController.scala
> +      case NotFoundError => NotFound(Json.toJson(errorWrapper))
No NotFoundError for this endpoint

2021-05-06 08:55 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +          (VrnFormatError, BAD_REQUEST),
The errors should only be         
```
val input = Seq(
          (VrnFormatError, BAD_REQUEST),
          (PeriodKeyFormatError, BAD_REQUEST),
          (DownstreamError, INTERNAL_SERVER_ERROR)
        )
```

2021-05-06 08:55 UTC, Taiwo-AB commented on test/v1/mocks/MockCurrentDateTime.scala
> + * Copyright 2021 HM Revenue & Customs
Please remove this file

2021-05-06 08:57 UTC, Taiwo-AB commented on test/v1/mocks/services/MockSubmitReturnRequestService.scala
> + *
Please refactor file and names to MockSubmitReturnService for consistency instead of MockSubmitReturn**Request**Service

2021-05-06 08:59 UTC, Taiwo-AB commented on it/v1/endpoints/SubmitReturnControllerISpec.scala
> +      val input = Seq(
Where are the other validation tests?

2021-05-06 09:13 UTC, Taiwo-AB commented on app/v1/controllers/SubmitReturnController.scala
> +  extends AuthorisedController(cc) with BaseController with Logging with AmendHateoasBodies {
Please remove `with AmendHateoasBodies` as it doesn't need it

2021-05-06 10:34 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    with MockAppConfig
Remove as it is not needed

2021-05-06 10:35 UTC, Taiwo-AB commented on test/v1/controllers/SubmitReturnControllerSpec.scala
> +    with MockAuditService {
Please remove as it is used

2021-05-06 13:43 UTC, merged